In [15]:
import numpy as np
import pandas as pd
from mace.data import LMDBDataset
from mace.calculators import mace_mp
from mace.tools.utils import AtomicNumberTable
from ase.io import read

In [16]:
# a = pd.DataFrame.from_records(np.load('/lustre/fswork/projects/rech/gax/ums98bp/descriptor_analysis/edge_info/salex.npy'))
a = pd.DataFrame.from_records(np.load('/lustre/fswork/projects/rech/gax/ums98bp/descriptor_analysis/edge_info/mptrj.npy'))
a.head()

dataset_index  edge_index_src  edge_index_dst  atomic_numbers  \
0             13               0              16               3   
1             13               0              21               3   
2             13               0              12               3   
3             13               0              16               3   
4             13               0              21               3   

   oxygen_distance  
0         3.527344  
1         5.257812  
2         5.261719  
3         3.527344  
4         5.257812

In [31]:
a.tail(200)

dataset_index  edge_index_src  edge_index_dst  atomic_numbers  \
307978            335              30               8              56   
307979            335              30              32               0   
307980            335              30               2              56   
307981            335              30              21               0   
307982            335              30              33               0   
...               ...             ...             ...             ...   
308173            335              34              25               0   
308174            335              34              14              23   
308175            335              34              20               0   
308176            335              34              26               0   
308177            335              34              32               0   

        oxygen_distance  
307978         5.171875  
307979         5.210938  
307980         4.960938  
307981         5.718750  
307982         5.156250  
...                 ...  
308173         5.148438  
308174         4.750000  
308175         5.023438  
308176         5.148438  
308177         5.222656  

[200 rows x 5 columns]

In [32]:
atoms[8]

Atom('Ba', [-1.2938771, -2.35511177, -5.99863998], index=8)

In [18]:
# lmdb
model = mace_mp('/lustre/fswork/projects/rech/gax/ums98bp/descriptor_analysis/test/medium-0b3.model', device='cpu', return_raw_model=True)
ds = LMDBDataset('/lustre/fsn1/projects/rech/gax/ums98bp/salex/train:/lustre/fsn1/projects/rech/gax/ums98bp/salex/val', 6., AtomicNumberTable([int(z) for z in model.atomic_numbers]))
atoms = ds.AseDB.get_atoms(a.loc[len(a)-1, 'dataset_index'])

# mptrj (xyz)
atoms = read('/lustre/fswork/projects/rech/gax/ums98bp/gga-ggapu/mptrj-all.xyz', a.loc[len(a)-1, 'dataset_index'])

Using float32 for MACECalculator, which is faster but less accurate. Recommended for MD. Use float64 for geometry optimization.


/lustre/fswork/projects/rech/gax/ums98bp/maces/main/mace/calculators/foundations_models.py:176: UserWarning: Environment variable TORCH_FORCE_NO_WEIGHTS_ONLY_LOAD detected, since the`weights_only` argument was not explicitly passed to `torch.load`, forcing weights_only=False.
  return torch.load(model_path, map_location=device)


In [21]:
atoms

Atoms(symbols='Ba12V4O19', pbc=True, cell=[[-3.70154376, -3.69179636, -5.99863998], [3.70154376, 3.69179636, -5.99863998], [7.39630579, -7.37682603, -0.0]], REF_forces=..., calculator=SinglePointCalculator(...))

In [22]:
a.iloc[-4], atoms.get_distances(int(a.iloc[-4].edge_index_src), int(a.iloc[-4].edge_index_dst))

(dataset_index      335.00
 edge_index_src      34.00
 edge_index_dst      14.00
 atomic_numbers      23.00
 oxygen_distance      4.75
 Name: 308174, dtype: float64,
 array([4.73962356]))

In [ ]:
a.iloc[-1].edge_index_src

49.0

NameError: name 'torch' is not defined

In [6]:
batch = next(iter(ds))

In [9]:
import torch
torch.bincount(batch.batch)


AttributeError: 'AtomicData' object has no attribute 'batch'

In [13]:
batch.batch[0]


AttributeError: 'AtomicData' object has no attribute 'batch'

In [23]:
from mace.tools.torch_geometric import DataLoader
dl = DataLoader(ds, batch_size=16)

In [25]:
batch = next(iter(dl))

In [26]:
batch.batch

tensor([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  2,
         2,  2,  2,  2,  2,  2,  2,  2,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
         3,  3,  3,  3,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,
         4,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  6,  6,
         6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
         7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
         7,  7,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  9,
         9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9, 10, 10, 10, 10,
        10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 11, 11, 11, 11, 11, 11, 11,
        11, 11, 11, 11, 11, 11, 11, 11, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
        12, 12, 12, 12, 12, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13,
        13, 13, 14, 14, 14, 14, 14, 14, 

In [ ]:

idx_offset = torch.cumsum(torch.bincount(batch.batch), dim=0)
idx_offset = torch.cat((torch.zeros(1, dtype=int), idx_offset))
torch.arange(len(batch.batch)) - idx_offset[batch.batch]

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14,  0,  1,  2,
         3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14,  0,  1,  2,  3,  4,  5,
         6,  7,  8,  9, 10, 11, 12, 13,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
        10, 11, 12, 13,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13,
        14,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14,  0,  1,
         2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
         0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14,  0,
         1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14,  0,  1,  2,  3,
         4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14,  0,  1,  2,  3,  4,  5,  6,
         7,  8,  9, 10, 11, 12, 13, 14,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
        10, 11, 12, 13, 14,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12,
        13, 14,  0,  1,  2,  3,  4,  5, 

In [39]:
torch.randn((2, len(idx_offset))) - idx_offset

tensor([[-5.3302e-01, -1.3623e+01, -3.1456e+01, -4.3794e+01, -5.6541e+01,
         -7.3208e+01, -8.7365e+01, -1.1021e+02, -1.2650e+02, -1.4393e+02,
         -1.5895e+02, -1.7299e+02, -1.8884e+02, -2.0309e+02, -2.1752e+02,
         -2.3373e+02, -2.4743e+02],
        [-7.6385e-03, -1.6036e+01, -2.9210e+01, -4.4238e+01, -5.8042e+01,
         -7.3863e+01, -8.8320e+01, -1.0917e+02, -1.2758e+02, -1.4390e+02,
         -1.5916e+02, -1.7356e+02, -1.8876e+02, -2.0293e+02, -2.1721e+02,
         -2.2997e+02, -2.4802e+02]])